/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Bren n_n
 */
public class MonstruitoGUI extends javax.swing.JFrame {

    /**
     * Creates new form MonstruitoGUI
     */
    int picados = 0;

    public MonstruitoGUI() {
        initComponents();
        double r;
        int ind = 0;
        String[] img = new String[2];
        img[0] = "/cliente/hole150.png";
        img[1] = "/cliente/azul150.png";
        JLabel[] celdas = new JLabel[9];
        celdas[0] = jLbl11;
        celdas[1] = jLbl12;
        celdas[2] = jLbl13;
        celdas[3] = jLbl21;
        celdas[4] = jLbl22;
        celdas[5] = jLbl23;
        celdas[6] = jLbl31;
        celdas[7] = jLbl32;
        celdas[8] = jLbl33;
        
        for(int i=0; i<9; i++){
            r = Math.random();
            if(r <=.5){
                ind = 0;
                celdas[i].setText("h");
            }
            else{
                ind = 1;
                celdas[i].setText("m");
            }
            celdas[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
        }

//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl11.setText("m");
//        }
//        //Object[] holes = [jLabel1, jLabel2];
//        jLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind]))); // NOI18N
//        
//        r = Math.random();
//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl13.setText("m");
//        }
//        jLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
//        
//        r = Math.random();
//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl12.setText("m");
//        }
//        jLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
//        
//        r = Math.random();
//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl23.setText("m");
//        }
//        jLbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
//        
//        r = Math.random();
//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl22.setText("m");
//        }
//        jLbl22.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
//        
//        r = Math.random();
//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl21.setText("m");
//        }
//        jLbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
//        
//        r = Math.random();
//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl33.setText("m");
//        }
//        jLbl33.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
//        
//        r = Math.random();
//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl32.setText("m");
//        }
//        jLbl32.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
//        
//        r = Math.random();
//        if (r <= .5) {
//            ind = 0;
//        } else {
//            ind = 1;
//            jLbl31.setText("m");
//        }
//        jLbl31.setIcon(new javax.swing.ImageIcon(getClass().getResource(img[ind])));
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl11 = new javax.swing.JLabel();
        jLbl13 = new javax.swing.JLabel();
        jLbl12 = new javax.swing.JLabel();
        jLbl23 = new javax.swing.JLabel();
        jLbl22 = new javax.swing.JLabel();
        jLbl21 = new javax.swing.JLabel();
        jLbl33 = new javax.swing.JLabel();
        jLbl32 = new javax.swing.JLabel();
        jLbl31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 0));
        setPreferredSize(new java.awt.Dimension(750, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 750));

        jLbl11.setBackground(new java.awt.Color(255, 255, 255));
        jLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl11.setText("h");
        jLbl11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl11MouseClicked(evt);
            }
        });

        jLbl13.setBackground(new java.awt.Color(255, 255, 255));
        jLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl13.setText("h");
        jLbl13.setAlignmentY(0.0F);
        jLbl13.setIconTextGap(0);
        jLbl13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl13MouseClicked(evt);
            }
        });

        jLbl12.setBackground(new java.awt.Color(255, 255, 255));
        jLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl12.setText("h");
        jLbl12.setAlignmentY(0.0F);
        jLbl12.setIconTextGap(0);
        jLbl12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl12MouseClicked(evt);
            }
        });

        jLbl23.setBackground(new java.awt.Color(255, 255, 255));
        jLbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl23.setText("h");
        jLbl23.setAlignmentY(0.0F);
        jLbl23.setIconTextGap(0);
        jLbl23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl23MouseClicked(evt);
            }
        });

        jLbl22.setBackground(new java.awt.Color(255, 255, 255));
        jLbl22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl22.setText("h");
        jLbl22.setAlignmentY(0.0F);
        jLbl22.setIconTextGap(0);
        jLbl22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl22MouseClicked(evt);
            }
        });

        jLbl21.setBackground(new java.awt.Color(255, 255, 255));
        jLbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl21.setText("h");
        jLbl21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl21MouseClicked(evt);
            }
        });

        jLbl33.setBackground(new java.awt.Color(255, 255, 255));
        jLbl33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl33.setText("h");
        jLbl33.setAlignmentY(0.0F);
        jLbl33.setIconTextGap(0);
        jLbl33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl33MouseClicked(evt);
            }
        });

        jLbl32.setBackground(new java.awt.Color(255, 255, 255));
        jLbl32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl32.setText("h");
        jLbl32.setAlignmentY(0.0F);
        jLbl32.setIconTextGap(0);
        jLbl32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl32MouseClicked(evt);
            }
        });

        jLbl31.setBackground(new java.awt.Color(255, 255, 255));
        jLbl31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/hole150.png"))); // NOI18N
        jLbl31.setText("h");
        jLbl31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl31MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLbl31, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl32, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl33, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(780, 780, 780))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl33, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl31, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl32, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbl11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl11MouseClicked
        System.out.println("lbl11 " + jLbl11.getText());
        if (jLbl11.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl11MouseClicked
//1a43bb1e
    private void jLbl12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl12MouseClicked
        System.out.println("lbl12 " + jLbl12.getText());
        if (jLbl12.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl12MouseClicked

    private void jLbl13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl13MouseClicked
        System.out.println("lbl13 " + jLbl11.getText());
        if (jLbl13.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl13MouseClicked

    private void jLbl21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl21MouseClicked
        System.out.println("lbl21 " + jLbl11.getText());
        if (jLbl21.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl21MouseClicked

    private void jLbl22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl22MouseClicked
        System.out.println("lbl22 " + jLbl11.getText());
        if (jLbl22.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl22MouseClicked

    private void jLbl23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl23MouseClicked
        System.out.println("lbl23" + jLbl23.getText());
        if (jLbl23.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl23MouseClicked

    private void jLbl31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl31MouseClicked
        System.out.println("lbl31 " + jLbl11.getText());
        if (jLbl31.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl31MouseClicked

    private void jLbl32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl32MouseClicked
        System.out.println("lbl32 " + jLbl11.getText());
        if (jLbl32.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl32MouseClicked

    private void jLbl33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl33MouseClicked
        System.out.println("lbl33 " + jLbl11.getText());
        if (jLbl33.getText().equals("m")) {
            envia();
        }
    }//GEN-LAST:event_jLbl33MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonstruitoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonstruitoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonstruitoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonstruitoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonstruitoGUI().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbl11;
    private javax.swing.JLabel jLbl12;
    private javax.swing.JLabel jLbl13;
    private javax.swing.JLabel jLbl21;
    private javax.swing.JLabel jLbl22;
    private javax.swing.JLabel jLbl23;
    private javax.swing.JLabel jLbl31;
    private javax.swing.JLabel jLbl32;
    private javax.swing.JLabel jLbl33;
    // End of variables declaration//GEN-END:variables

    private void envia() {
        Socket s = null;
        try {
            int serverPort = 7897;
            s = new Socket("localhost", serverPort);
            //   s = new Socket("127.0.0.1", serverPort);    
            DataInputStream in = new DataInputStream(s.getInputStream());
            DataOutputStream out
                    = new DataOutputStream(s.getOutputStream());
            out.writeUTF("Hello," + picados);        	// UTF is a string encoding 

            String data = in.readUTF();
            String[] d;
            d = data.split(",");
            //out.writeUTF("Hello," + picados);        	// UTF is a string encoding 

            System.out.println("Received: " + d[0] + " ," + d[1]);
        } catch (UnknownHostException e) {
            System.out.println("Sock:" + e.getMessage());
        } catch (EOFException e) {
            System.out.println("EOF:" + e.getMessage());
        } catch (IOException e) {
            System.out.println("IO:" + e.getMessage());
        } finally {
            if (s != null) {
                try {
                    s.close();
                } catch (IOException e) {
                    System.out.println("close:" + e.getMessage());
                }
            }
        }

    }
}
